### ISSUE TITLE
Auto generated tra offset from correct projection

### ISSUE THREAD

**Issue by amymmorton** [BrownBiomechanics/SlicerAutoscoperM#107]
![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/aff05918-3914-4415-8a25-c1dff34a38a6)
Using BN00107.

bone coloured volume rendering is a clone of neutral, with invert Origin2DICOM applied.

Yellow segmented stls

Grey - neutral volume rendering (dciom space)

Green in mc1 with (invert) tra applied

![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/b0d19463-eca2-4bc1-b53c-80d7dbac2085)

**Comment by NicerNewerCar** [comment]
A few clarification points

- TRA output from the PV gen is in DICOM space but the VRGs are in AUT space?
- I am assuming the yellow? volumes are the ones aligned with the dicom space CT and the green? is the one floating off to the side (I am yellow-green colorblind😢)
- Red is the TIFF loaded in with no transform applied?

**Comment by amymmorton** [comment]
TRA output is from pv gen- yes but they should be in AUT space. 


I'm sorry - no more yellow green! oops but yes you're correct. For clarity: here is the (previously green) now blue mc1 translformed from AUT_partial volume by tra inverse
![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/65619862/196ce09c-c800-4b06-aeda-730bf31a4f99)


Yes- red was not modified- its the bone model of where the tiff would be with correct spatial dimensions and no translation. 


What should be shown: overlay of the now blue mc1 on the bone-colored neut copy (since it's been transformed by inverse origin2dicom)

**Comment by NicerNewerCar** [comment]
A few things

For the tra not aligining in Autoscoper
- Generate the Origin2Dicom (if not already generated) at the time of PV gen
    - If the user generates the PVs before the VRGs the Origin2Dicom transform won't get generated and then won't be applied to the tra
    - I will add some UI toggle box for the PV generation to enable whether or not this gets used/generated. (Default to on)
        - For the case of manual camera placement since auto centerting is no performed during this pipeline 


For not being able to load tras back into Slicer
- Slicer2AUT and AUT2Slicer transforms are different

Similar to your images above grey neutral is in dicom space and the white neutral is in slicer world centered space.

#### Creating the TRA file
To create the TRA file for a PV the following steps are taken.
1. Get the PV Origin
![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/30351234/5278ec09-3039-4476-b870-7014935d8861)
2. Apply the Dicom2Origin transform (Inverse Origin2Dicom). This moves the mc1 from dicom space into the centered worldspace. Note this is **NOT** Autoscoper space just yet
![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/30351234/7df98a57-af83-4803-ba83-e0794fa5ed8e)
3. Apply the Slicer2Aut transform (Rotate 180 degress on the Roll / X-axis and offset the translation by volSize * volSpacing for the -X direction)

| Slicer Centered World Space | Autoscoper Space |
| ------------------------------- | --------------------|
| ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/30351234/c677e40f-2a3b-4693-986a-4697353e7888) | ![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/30351234/e0394299-6fb1-4b73-a2e3-7c9de9d19d23) |

#### Loading the TRA file back into Slicer
1. Load TIFF stack of desired volume (Origin at the world center) CT volumes were hidden for clarity. 
![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/30351234/b74f6ba1-05e9-4a39-9ac5-2a550655ceea)

2. Create a transform node from the tra file
```python
# Small script to convert a tra file to a Slicer transform :) 
# Just Copy and paste this into the slicer terminal
# Make sure to change both of the names in brackets
import numpy as np
import vtk
from itertools import product
tra = np.loadtxt(<file>, delimiter=",")
# tra = tra[0] # If there are multiple frames uncomment and change 0 to your frame
tra = tra.reshape(4,4)
mat = vtk.vtkMatrix4x4()
for i,j in product(range(4), range(4)):
  mat.SetElement(i,j, tra[i,j])
tfmNode = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLTransformNode", <node name>) 
tfmNode.SetMatrixTransformToParent(mat)
```
3. Apply the AUT2Slicer transform to the PV (Rotate 180 degress on the Yaw / Z-Axis and offset translationaly by volDim * volSpacing in the +X direction)
![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/30351234/a0c42bed-fc03-4f35-93b6-90d736a4ee3b)
4. Apply the transform loaded in from the TRA file
![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/30351234/c22f5d82-07d4-4c91-9ce8-ea81f69fdcf0)


# TODO
- [ ] Generate the Origin2Dicom (if not already generated) at the time of PV gen
- [ ] Export Slicer2AUT transforms for each PV 
- [ ] Export the AUT2Slicer transform

**Comment by amymmorton** [comment]
The PV, its tfm and its tra need to exist  in bvr and 3dct...  (in cases with vrg gen and without)....

So perhaps we require camera calibration prior to allowing pv generation?

**Comment by NicerNewerCar** [comment]
> The PV, its tfm and its tra need to exist in bvr and 3dct... (in cases with vrg gen and without)....
> 
> So perhaps we require camera calibration prior to allowing pv generation?

Makes sense, I will put together a pop up that will let the user know that, for the case of the auto camera placement, they are required to run that prior to generating the PVs

**Comment by amymmorton** [comment]
Thanks, Anthony,

I will add a standalone issue for this as well, but I believe we should
rearrange the pre-processing tabs, such that the segmentation and partial
volumes are one after the other


-----------
Amy Morton, MSc

Sr. Research Engineer, Bioengineering Lab, Department of Orthopaedic
Research
The Warren Alpert Medical School of Brown University and Rhode Island
Hospital
1 Hoppin Street, CORO West, Ste. 404, Providence, RI 02903
