### ISSUE TITLE
Support for evaluating the accuracy of the tracking

### ISSUE THREAD

**Issue by jcfr** [BrownBiomechanics/SlicerAutoscoperM#32]
![image](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/219043/ccec8884-f218-4a08-bb59-7a4a041c5867)

References:
* https://github.com/skelobslab/JOVE_BVR_FootModelAndMarkerBased
* https://www.jove.com/t/63535/biplanar-videoradiography-dataset-for-model-based-pose-estimation

**Comment by NicerNewerCar** [comment]
Should this be a standalone module or be integrated as library code, similar to what I am doing with PR #12?

**Comment by bpaniagua** [comment]
Might be easier to do stand alone (just like the import modules you created from matlab) and integrate later on if needed. My 0.02

**Comment by NicerNewerCar** [comment]
TODO:

- [ ] Support loading partial volumes, tracking data, and GT tracking data into Slicer.
- [ ] Visualize the movement of the partial volumes.
- [ ] Visualize the difference between the tracking data and GT data (see diagram above).
    - [ ] Models should be green iff the difference is within some tolerance (ie. 1mm or 2 deg).
    - [ ] Models should be red otherwise
- [ ] Update the [tutorial](https://autoscoper--117.org.readthedocs.build/en/117/tutorials/sample-data.html) or create a new one to cover the usage of this module.
- [ ] Update the Sample data to include GT tracking data.
    - [ ] Need to update the [release](https://github.com/BrownBiomechanics/Autoscoper/releases/tag/sample-data) in autoscoper main.
    - [ ] Need to update checksum verification in SA^M:
https://github.com/BrownBiomechanics/SlicerAutoscoperM/blob/13ae181309b949420dc06c1bac2f894d63f3a3f9/AutoscoperM/AutoscoperM.py#L104-L116

**Comment by NicerNewerCar** [comment]
Just need to package the new sample data and append a new section to the tutorial, on how to use this module.

![eval](https://github.com/BrownBiomechanics/SlicerAutoscoperM/assets/30351234/b5967373-8f0a-4b54-83e8-83935ba0a990)

**Comment by amymmorton** [comment]
- [ ]  using Partial Volume Femur and Tibia tif generated from [Pvol](https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/12), use the .tra files from @jdholt04 (to be uploaded [v.1.4](https://github.com/BrownBiomechanics/Autoscoper/releases/tag/extendedSampleData))
