### ISSUE TITLE
ASB 2023 Progress tracker

### ISSUE THREAD

**Issue by NicerNewerCar** [BrownBiomechanics/SlicerAutoscoperM#39]
This issue will be utilized to track the progress of all required integrations (both Autoscoper and SlicerAutoscoper) and other tasks for ASB 2023.

If I missed anything @jcfr @amymmorton @bpaniagua please don't hesitate to edit this comment and add anything to the lists below, just make sure you ping me (either on github or through my email) so I am aware of any changes.

## Autoscoper Base

- Issues
  - [x] [#132](https://github.com/BrownBiomechanics/Autoscoper/pull/132) https://github.com/BrownBiomechanics/Autoscoper/pull/132
  - [x] [#162](https://github.com/BrownBiomechanics/Autoscoper/pull/162) https://github.com/BrownBiomechanics/Autoscoper/pull/162
  - [x] [#176](https://github.com/BrownBiomechanics/Autoscoper/ipull/176) https://github.com/BrownBiomechanics/Autoscoper/pull/176
  - [x] [#180](https://github.com/BrownBiomechanics/Autoscoper/pull/180) https://github.com/BrownBiomechanics/Autoscoper/pull/180
- Features
  - [x] [#125](https://github.com/BrownBiomechanics/Autoscoper/pull/125) https://github.com/BrownBiomechanics/Autoscoper/pull/125
- Usability
  - [x] [#141](https://github.com/BrownBiomechanics/Autoscoper/pull/141) https://github.com/BrownBiomechanics/Autoscoper/pull/141
  - [x] [#133](https://github.com/BrownBiomechanics/Autoscoper/pull/133) https://github.com/BrownBiomechanics/Autoscoper/pull/133
  - [x] [#148](https://github.com/BrownBiomechanics/Autoscoper/pull/148) https://github.com/BrownBiomechanics/Autoscoper/pull/148
  - [x] [#153](https://github.com/BrownBiomechanics/Autoscoper/pull/153) https://github.com/BrownBiomechanics/Autoscoper/pull/153
  - [x] [#165](https://github.com/BrownBiomechanics/Autoscoper/pull/165) https://github.com/BrownBiomechanics/Autoscoper/pull/165
- Tutorials
  - [x] [#142](https://github.com/BrownBiomechanics/Autoscoper/pull/142) https://github.com/BrownBiomechanics/Autoscoper/pull/142
  - [x] [#151](https://github.com/BrownBiomechanics/Autoscoper/pull/151) https://github.com/BrownBiomechanics/Autoscoper/pull/151
- Dataset
  - [x] Finalize and release new sample data.

## Autoscoper extension 

- Features
  - [x] #12
  - [x] #33
- Issues
  - [x] #37
- Dependencies
  - [x] https://github.com/BrownBiomechanics/SlicerAutoscoperM/pull/41
    - [x] Update PyAutoscoper version to `v2.0.0`. See [AutoscoperM/AutoscoperM.py](https://github.com/BrownBiomechanics/SlicerAutoscoperM/blob/80097e2be7d4078f160f9386879a637a6d194f4f/AutoscoperM/AutoscoperM.py#L412-L422)
    - [x] Edit the commit of Autoscoper being pulled once everything is integrated. See [SuperBuild/External_Autoscoper.cmake](https://github.com/BrownBiomechanics/SlicerAutoscoperM/blob/80097e2be7d4078f160f9386879a637a6d194f4f/SuperBuild/External_Autoscoper.cmake#L32-L36)
- [x]  [#1959](https://github.com/Slicer/ExtensionsIndex/pull/1959) https://github.com/Slicer/ExtensionsIndex/pull/1959

## Other tasks

- [x] Release PyAutoscoper ~~v1.2.0~~ v2.0.0 once [#132](https://github.com/BrownBiomechanics/Autoscoper/pull/132)  and [#119](https://github.com/BrownBiomechanics/Autoscoper/pull/119) are integrated
  - https://github.com/BrownBiomechanics/Autoscoper/pull/132
  - https://github.com/BrownBiomechanics/Autoscoper/pull/119
- [x] Script for demo
- [x] Record videos of demo for backup
